name = "SignatureGB"
uuid = "43426ac7-8856-4fa2-b237-3d89f9853cab"
authors = ["Rafael Mohr <Rafael.Mohr@lip6.fr> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
